// Implement any 15 string methods on the String “The Phoenix Guild is the best Women in Web3 Community”
var s = "The Phoenix Guild is the best Women in Web3 Community";
console.log(s.charAt(10));
//console.log(charCodeAt(2));
var s1="The Phoenix Guild is the best Women";
var s2="in Web3 Community";
var s3=s1.concat(s2);
console.log(s3);
var s4=s.indexOf("the");
console.log(s4);
var s5=s.lastIndexOf("Women");
console.log(s5);
var s6=s.toLowerCase();
console.log(s6);
var s7=s.toUpperCase();
console.log(s7);
var s8=s.length;
console.log(s8);
var s9=s.slice(12,20);
console.log(s9);
var s10=s.trim();
console.log(s10);
console.log(s.split(" "));
var s11=s.toLocaleUpperCase();
console.log(s11);
var s12=s.toLocaleLowerCase();
console.log(s12);
var s13= s.replace("best","better");
console.log(s13);
console.log(s.search("the"));
console.log(s.match("the"));